---
- name: Booting to Network Operating System image
  block:
    - name: Booting to Network Operating System image
      dellemc.openmanage.idrac_os_deployment:
        validate_certs: false
        idrac_ip: "{{ item }}"
        idrac_user: "{{ idrac_user }}"
        idrac_password: "{{ idrac_password }}"
        share_name: "{{ iso_path }}"
        iso_image: "{{ iso_name }}"
        expose_duration: 180
      register: os_deployment
      delegate_to: "{{ item }}"
      with_items:
        - "{{ idrac_details }}"    

  rescue:
    - debug:
        msg: "IDRAC OS provisioning failed"  
  tags:
    - network_iso




 
      
